version: '3.9'

services:
  db:
    image: postgres:16-alpine   # Alpine Linux
    container_name: api_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petmatch_dev
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
